{% set name = "xontrib-xlsd" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a86f0da0b1b1c2bf2709ef67a89ab601a04cad7b4496a9925a6fc8bce4efb948

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xonsh
    - wcwidth
    - python-magic

test:
  commands:
    - xonsh -c "import xontrib.xlsd"

about:
  home: https://github.com/cafehaine/xontrib-xlsd/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  dev_url: https://github.com/cafehaine/xontrib-xlsd/

extra:
  recipe-maintainers:
    - scopatz
